all:
  hosts:
    oversearch_container:
      ansible_host: 172.17.0.6
      ansible_user: root
      ansible_ssh_private_key_file: configs/private_ssh.key
      ansible_python_interpreter: /usr/bin/python3