---

- name: Устанавливаем необходимые пакеты
  apt:
    pkg:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libgdbm-dev
      - libdb5.3-dev
      - libbz2-dev
      - libexpat1-dev
      - liblzma-dev
      - tk-dev
      - libffi-dev
    state: latest
    update_cache: true

- name: Скачиваем исходный код
  unarchive:
    src: "https://www.python.org/ftp/python/{{python_version}}/Python-{{python_version}}.tgz"
    dest: /usr/src
    remote_src: yes

- name: Конфигурируем
  command:
    cmd: "./configure --enable-optimizations"
    chdir: "/usr/src/Python-{{python_version}}"

- name: Собираем
  command: 
    cmd: "make"
    chdir: "/usr/src/Python-{{python_version}}"

- name: Устанавливаем
  command: 
    cmd: "make install"
    chdir: "/usr/src/Python-{{python_version}}"
