---
- name: Устанавливаем gunicorn
  become: yes
  become_user: "{{ default_user }}"
  become_method: su
  pip:
    name: gunicorn
    virtualenv: "{{ venv_path }}"
    state: latest

- name: Создаём директорию для лог файлов gunicorn
  file:
    path: "/var/log/gunicorn"
    state: directory
    mode: '0755'
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
